### ISSUE TITLE
cannot find function parse_to_serde_value

### ISSUE THREAD

**Issue by massivefermion** [dprint/jsonc-parser#20]
I'm trying it use `parse_to_serde_value` but I get this error:
`error[E0425]: cannot find function parse_to_serde_value in crate jsonc_parser`
It's really weird because the function is clearly there and all I'm doing is just calling it using `jsonc_parser::parse_to_serde_value`.
Another weird thing is, when I start typing `parse_to_serde_value` inside `use jsonc_parser::{}`, vscode starts recommending it but then after I accept it, it just says `no parse_to_serde_value in the root`!
What's going on?

**Comment by dsherret** [comment]
Sorry, it's not documented well. Use the "serde" feature:

```toml
jsonc-parser = { version = "0.17.0", features = ["serde"] }
```
