### ISSUE TITLE
Method on ast::Value to get the range

### ISSUE THREAD

**Issue by kitsonk** [dprint/jsonc-parser#27]
All of the variants of `ast::Value` contain a `range: common::Range`, but consumers currently have to pattern match all the variants to be able to extract the range, where a `.range()` methods could make that easy.

**Comment by dsherret** [comment]
Should implement Range. Try importing that trait https://github.com/dprint/jsonc-parser/blob/bfee0d972fb3a002568f60de8b224ce72ebef2fb/src/ast.rs#L367

**Comment by kitsonk** [comment]
doh! 🤦

**Comment by dsherret** [comment]
Yeah traits are annoying for discoverability if the language server lets you down lol

**Comment by kitsonk** [comment]
yeah, importing `Ranged` works like a charm.
