### ISSUE TITLE
Implement std::error::Error for ParseError

### ISSUE THREAD

**Issue by bartlomieju** [dprint/jsonc-parser#3]
Using the lib I encountered a bit surprising behavior where `ParseError` doesn't implement `std::error::Error`. It makes handling a bit unwieldy.

```
error[E0277]: the trait bound `jsonc_parser::errors::ParseError: std::error::Error` is not satisfied
   --> cli/tsc_config.rs:147:15
    |
147 |   let jsonc = jsonc_parser::parse_to_value(config_text.as_ref()).map_err(ErrBox::from)?.unwrap();
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `jsonc_parser::errors::ParseError`
```

Also, why is ok  return value from `parse_to_value` an `Option<JsonValue>` instead of just `JsonValue`?

**Comment by dsherret** [comment]
I was thinking this the other day and came across a similar issue using dprint-plugin-typescript about 5 mins ago 😂. It’s because I didn’t/still don’t really understand Error. This would be a good change... do you have the time to implement it properly to show me how it’s done?

It returns an Option because the file might be empty.

**Comment by bartlomieju** [comment]
> I was thinking this the other day and came across a similar issue using dprint-plugin-typescript about 5 mins ago 😂. It’s because I didn’t/still don’t really understand Error. This would be a good change... do you have the time to implement it properly to show me how it’s done?

It's just a blanket trait - it requires to implement `Display` on the struct implementing `Error` - I guess the only purpose of that trait is to have "idiomatic" handling of errors. Sure, I can open a PR.

> It returns an Option because the file might be empty.

Thanks that makes sense

**Comment by dsherret** [comment]
Oh! I am just remembering the `get_message_with_range` thing. It would be nice if it did that by default always. Perhaps the current error can be renamed and returned in the lower level functions and then the top level functions can return a `ParseError` that has the message with the range. I'm not sure what's best though (this is more complicated than I remember... I can do it when I get back from lunch if you're not up for it).

**Comment by bartlomieju** [comment]
@dsherret I'm gonna change `ParseError` not to have `get_message_with_range()` - I will perform that logic when creating `ParseError`

**Comment by bartlomieju** [comment]
@dsherret you were faster! Whichever for works for you better

**Comment by dsherret** [comment]
@bartlomieju awesome! Yeah, if you have it figured out already then that would be super helpful!

**Comment by bartlomieju** [comment]
@dsherret my approach would need to store whole `text` on one of `Scanner`/`Context`. I'm not sure if that's a valid approach...

**Comment by dsherret** [comment]
@bartlomieju FYI, I did a 0.14.0 release because I needed to keep the error message property not having the range for dprint-plugin-json. It should still display with the range when doing `parse_to_value(...)?` though.
